//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tFields()
        {
            this.tFieldValues = new HashSet<tFieldValues>();
            this.tCycle = new HashSet<tCycle>();
        }
    
        public int FieldID { get; set; }
        public string Name { get; set; }
        public string ImportColumnName { get; set; }
        public string ChiliVariableName { get; set; }
        public string Type { get; set; }
        public int SortOrder { get; set; }
        public string DefaultValue { get; set; }
        public string AllowedValues { get; set; }
        public int NumLines { get; set; }
        public int InstanceID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFieldValues> tFieldValues { get; set; }
        public virtual tInstances tInstances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCycle> tCycle { get; set; }
    }
}
