//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAA.Entities.VAAEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRoles()
        {
            this.tUserRoles = new HashSet<tUserRoles>();
        }
    
        public int RoleID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> CanViewUpperClass { get; set; }
        public Nullable<bool> CanViewPremiumEconomy { get; set; }
        public Nullable<bool> CanViewEconomy { get; set; }
        public Nullable<bool> CanEditUpperClass { get; set; }
        public Nullable<bool> CanEditPremiumEconomy { get; set; }
        public Nullable<bool> CanEditEconomy { get; set; }
        public Nullable<bool> CanDeleteUpperClass { get; set; }
        public Nullable<bool> CanDeletePremiumEconomy { get; set; }
        public Nullable<bool> CanDeleteEconomy { get; set; }
        public Nullable<bool> CanApproveUpperClass { get; set; }
        public Nullable<bool> CanApprovePremiumEconomy { get; set; }
        public Nullable<bool> CanApproveEconomy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tUserRoles> tUserRoles { get; set; }
    }
}
